version: "3"
services:
  backend:
    build: ./dao-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend
  frontend:
    build: ./dao-frontend
    ports:
      - "3000:3000"
